module.exports = [
  {
    "name" : "測試",
    "jsName" : "checkNotifyStatusJob",
    "description" : "測試說明",
    "cron" : "*/3 * * * * *",
    "active" : false,
  },
  {
    "name" : "檢查門診時間",
    "jsName" : "checkOutpatientTimeJob",
    "description" : "定時檢查門診時間是否開始, 驅動提醒通知",
    "cron" : "0 */1 * * * *",
    "active" : true,
  },  
  {
    "name" : "每日錄影檔下載並分類",
    "jsName" : "downloadMeetingRecordJob",
    "description" : "後台每日定時將前一天錄影檔下載至FTPServer並依醫院和日期分類",
    //"cron" : "0 */1 * * * *",
    "cron" : "0 0 2 * * *",
    "active" : true,
  },  
  {
    "name" : "前一天門診時間提醒",
    "jsName" : "noteOutpatientTheDayBeforeJob",
    "description" : "每天檢查明天是否有門診, 並驅動提醒通知",
    //"cron" : "*/15 * * * * *",
    "cron" : "0 0 20 * * *",
    "active" : true,
  }, 
  {
    "name" : "每日掛號報價扣款",
    "jsName" : "dailyPaymentJob",
    "description" : "每天檢查當日已報價掛號, 並進行扣款",
    //"cron" : "0 */1 * * * *",
    "cron" : "0 0 23 * * *",
    "active" : false,
  }, 
  {
    "name" : "檢查醫病溝通開始時間",
    "jsName" : "checkCommunicateTimeJob",
    "description" : "定時檢查醫病溝通時間是否開始, 驅動提醒通知",
    "cron" : "0 */1 * * * *",
    //"cron" : "*/20 * * * * *",
    "active" : true,
  }, 
  {
    "name" : "檢查影像檔是否異常",
    "jsName" : "getConsultingRecordsAndCheckFileUrlJob",
    "description" : "定時取得影像檔報表資料並檢查影像檔資料是否存在異常，如異常則寄送Email通知維運人員。",
    "cron" : "0 0 */1 * * *",
    // "cron" : "*/20 * * * * *",
    "active" : true,
  },
  {
    "name" : "彙整前一日影像檔資料並通知維護人員",
    "jsName" : "dailyGetConsultingRecordsAndEmailInfoJob",
    "description" : "取得影像檔報表資料，依據醫院進行資料統計及彙整並寄送Email通知維運人員。",
    "cron" : "0 30 1 * * *",
    // "cron" : "*/10 * * * * *",
    "active" : true,
  },
]
